name: Build Capstone with Java Bindings

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'  # 或者你需要的 Java 版本

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc g++ make

      - name: Build Capstone
        run: |
          git clone https://github.com/aquynh/capstone.git
          cd capstone
          mkdir build && cd build
          cmake ..
          make
          sudo make install

      - name: Build Java Bindings
        run: |
          cd capstone/bindings/java
          javac -d out src/*.java
          cd out
          jar cf capstone.jar *.class

      - name: Upload Capstone JAR
        uses: actions/upload-artifact@v2
        with:
          name: capstone-java
          path: capstone/bindings/java/out/capstone.jar
